source 'https://rubygems.org'

gem 'rails'
gem 'sqlite3'

group :development do
  gem 'web-console'
  gem 'guard'
  gem 'guard-minitest'
end

group :test do
  gem 'capybara'
  gem 'launchy'
end

group :development, :test do
  gem 'pry-rails'
end
